version: '3.1'

services:
  frontend:
    image: lister-front:1 
    restart: always
    depends_on:
      - backend
    ports:
      - 93:80

  backend:
    image: lister-back:1.2
    restart: always
    depends_on:
      - mongodb 
    ports:
      - 1200:1200         

  mongodb:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb